---

- name: SET_FACT | Bypass https://github.com/ansible/ansible/issues/19874
  ansible.builtin.set_fact:
    ansible_distribution_release: 'buster'
  when: ansible_facts.distribution_major_version == "buster/sid"

- name: APT | Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: APT | Install nginx and dependencies
  ansible.builtin.apt:
    pkg: "{{ nginx_apt_package }}"
    default_release: "{{ ansible_distribution_release + '-backports' if (nginx_backports and ansible_distribution == 'Debian') else ansible_distribution_release }}"

- name: APT | Install nginx modules
  ansible.builtin.apt:
    pkg: "{{ nginx_module_packages }}"
    state: present

- name: APT | Install passlib lib
  ansible.builtin.apt:
    pkg: "python3-passlib"
    state: present
