---

- name: TEMPLATE | Deploy nginx.conf
  template: >
    src=etc/nginx/nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: TEMPLATE | Deploy all helpers
  template: >
    src={{ item }}
    dest={{ nginx_helper_dir }}/{{ item | basename | regex_replace('\.j2$','') }}
  with_fileglob: '../templates/etc/nginx/helper/*.j2'
  notify: reload nginx

- name: TEMPLATE | Deploy custom http configuration
  template: >
    src=etc/nginx/conf.d/custom.conf.j2
    dest=/etc/nginx/conf.d/custom.conf
  notify: reload nginx

