---

- name: FAIL | Check possible issues
  fail:
    msg: "This ansible version ({{ ansible_version.full}}) is not compatible with your needs (Debian Stretch + htpasswd). Please see https://github.com/HanXHX/ansible-nginx/issues/28"
  when:
    ansible_distribution_major_version >= 9 and
    ansible_version.full | version_compare('2.3.2', 'lt') and
    nginx_htpasswd | length > 0

- name: APT | Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: false

- name: APT | Force OpenSSL from backports (fix dependency break)
  apt:
    pkg: openssl
    state: latest
    default_release: "{{ ansible_distribution_release + '-backports' }}"
  when: nginx_backports

- name: APT | Install nginx and dependencies
  apt:
    pkg: "{{ nginx_apt_package }}"
    state: present
    default_release: "{{ ansible_distribution_release + '-backports' if nginx_backports else ansible_distribution_release }}"

- name: APT | Install python-passlib
  apt:
    pkg: python-passlib
    state: present
