---

- name: PKGNG | Install nginx and related tools
  pkgng:
    name: "{{ item }}"
    state: present
  loop:
    - acme.sh
    - "{{ nginx_pkgng_package }}"
    - py27-passlib
    - curl

#
# Bypass https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224166#c1
#
- block:

    - name: COMMAND | Create /usr/local/etc/fdfs/http.conf
      command: touch /usr/local/etc/fdfs/http.conf
      args:
        creates: /usr/local/etc/fdfs/http.conf
      register: fd1

    - name: LINEINFILE | Tune fdfs
      lineinfile:
        regexp: ^load_fdfs_parameters_from_tracker
        line: load_fdfs_parameters_from_tracker=false
        path: /usr/local/etc/fdfs/mod_fastdfs.conf
      register: fd2

    - name: SERVICE | Restart nginx when fdfs is tuned
      service:
        name: nginx
        state: restarted
      when: fd1.changed or fd2.changed

  when: true

- name: FILE | Create configuration dir (like Debian)
  file:
    path: "{{ nginx_etc_dir }}/{{ item }}"
    state: directory
  loop:
    - conf.d
    - sites-available
    - sites-enabled

- name: FILE | Create log directory
  file:
    path: "{{ nginx_log_dir }}"
    owner: "{{ nginx_user }}"
    group: wheel
    mode: 0755
    state: directory

- name: SERVICE | Enable nginx
  service:
    name: nginx
    enabled: true
