---

- name: INCLUDE_VARS | Related to OS
  include_vars: "{{ ansible_distribution }}.yml"
  tags: ['nginx::site', 'nginx::ssl']

- name: INCLUDE | Install
  include: "install_{{ ansible_distribution }}.yml"
  tags: ['nginx::site', 'nginx::ssl']

- name: INCLUDE | Prepare
  include: prepare.yml
  tags: ['nginx::site', 'nginx::ssl']

- name: INCLUDE | Install
  include: config.yml

- name: INCLUDE | Upstream configuration
  include: upstream.yml

- name: INCLUDE | htpasswd configuration
  include: htpasswd.yml

- name: INCLUDE | SSL configuration
  include: ssl/main.yml
  tags: ['nginx::ssl']

- name: INCLUDE | Sites configuration
  include: site.yml
  tags: ['nginx::site']
