---

- name: INCLUDE | Install
  include: install.yml

- name: INCLUDE | Prepare
  include: prepare.yml

- name: INCLUDE | Install
  include: config.yml

- name: INCLUDE | Upstream configuration
  include: upstream.yml
  when: nginx_php

- name: INCLUDE | htpasswd configuration
  include: htpasswd.yml

- name: INCLUDE | Vhosts configuration
  include: ssl.yml

- name: INCLUDE | Vhosts configuration
  include: vhost.yml

