---

- name: SHELL | Get module list
  shell: nginx -V 2>&1 | tr -- - '\n' | grep -A 1 with | grep _module | sed -r 's/_module//g; s/\s+//g' | sort
  args:
    executable: /bin/sh
  register: shell_modules
  changed_when: false
  check_mode: no

- name: SET_FACT | Save modules
  set_fact:
    nginx_modules: "{{ shell_modules.stdout_lines }}"

- name: FILE | Create folders
  file:
    dest: "{{ item.dir }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items: "{{ nginx_dirs }}"

- name: FILE | Create ansible facts dir
  file:
    path: /etc/ansible/facts.d
    state: directory
