---

- name: SET_FACT | Backward compatibility with old version of this role
  set_fact: >
    nginx_php56: true
  when: nginx_php is defined and nginx_php

- name: TEMPLATE | Deploy PHP upstream to Nginx
  template: >
    src=etc/nginx/upstream/php.conf.j2
    dest="{{ nginx_etc_dir }}/conf.d/php.conf"
  when: nginx_php56 or nginx_php70
  notify: reload nginx

- name: TEMPLATE | Deploy other upstreams
  template: >
    src=etc/nginx/upstream/upstream.conf.j2
    dest={{ nginx_etc_dir }}/conf.d/upstream-{{ item.name }}.conf
  with_items: "{{ nginx_upstreams }}"
  when: item.state is not defined or item.state == 'present'
  notify: reload nginx

- name: FILE | Delete other upstreams
  file: >
    path={{ nginx_etc_dir }}/conf.d/upstream-{{ item.name }}.conf
    state=absent
  with_items: "{{ nginx_upstreams }}"
  when: item.state is defined and item.state == 'absent'
  notify: reload nginx
