---

platforms:
  - name: ubuntu-20.04
    image: dokken/ubuntu-20.04
    command: /lib/systemd/systemd
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true

# Segfault on Ubuntu 20.04 with `nginx-extras` package...
provisioner:
  inventory:
    host_vars:
      ubuntu-20.04:
        nginx_apt_package: 'nginx-full'
