---

nginx_apt_package: nginx-full

#
# Nginx shared variables
#
nginx_root: "/srv/www"
nginx_log_dir: '/var/log/nginx'
nginx_ssl_dir: '/etc/nginx/ssl'
nginx_pid: '/run/nginx.pid'
nginx_resolver:
  hosts: ['8.8.8.8', '8.8.4.4']
  valid: '300'
  timeout: '5'
nginx_error_log_level: 'warn' # http://nginx.org/en/docs/ngx_core_module.html#error_log
nginx_dh_length: 2048


#
# Load upstream
#

# PHP
nginx_php: false
nginx_php_sockets:
  - unix_socket: "/var/run/php5-fpm.sock"
nginx_upstreams: []

#
# Nginx configuration
#
nginx_user: 'www-data'
nginx_worker_processes: '{{ ansible_processor_vcpus }}'

#
# Nginx events
#
nginx_events_worker_connections: '512'
nginx_events_multi_accept: 'on'
nginx_events_use: 'epoll'

#
# Nginx HTTP
#
nginx_http_types_hash_max_size: 2048
nginx_http_default_type: 'application/octet-stream'
nginx_http_access_log: 'off'
nginx_http_error_log: 'off'
nginx_http_client_body_buffer_size: '1M'
nginx_http_client_header_buffer_size: '1M'
nginx_http_client_max_body_size: '10M'
nginx_http_large_client_header_buffers: '8 8k'
nginx_http_client_body_timeout: '60'
nginx_http_client_header_timeout: '60'
nginx_http_keepalive_timeout: '30 30'
nginx_http_send_timeout: '120'
nginx_http_ignore_invalid_headers: 'on'
nginx_http_keepalive_requests: '100'
nginx_http_recursive_error_pages: 'on'
nginx_http_sendfile: 'on'
nginx_http_server_name_in_redirect: 'off'
nginx_http_server_tokens: 'off'
nginx_http_tcp_nodelay: 'on'
nginx_http_tcp_nopush: 'on'
nginx_http_reset_timedout_connection: 'on'
nginx_http_gzip: 'on'
nginx_http_gzip_buffers: '16 8k'
nginx_http_gzip_comp_level: '9'
nginx_http_gzip_http_version: '1.0'
nginx_http_gzip_min_length: '0'
nginx_http_gzip_types: 'text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml'
nginx_http_gzip_vary: 'on'
nginx_http_gzip_disable: '"msie6"'

#
# nginx_http_custom
#
nginx_http_custom: []

#
# Vhosts
#
nginx_vhosts: []

#
# htpasswd
#
nginx_htpasswd: []
