---

# Reload wrapper
- name: reload nginx
  command: nginx -t
  notify: real-reload nginx

- name: real-reload nginx
  service: name=nginx state=reloaded

- name: restart nginx freebsd
  service: name=nginx state=restarted
  when: ansible_distribution == "FreeBSD"
