---

- name: reload nginx
  command: nginx -t
  notify: real-reload nginx

- name: restart nginx
  command: nginx -t
  notify: real-restart nginx

- name: real-reload nginx
  service:
    name: nginx
    state: reloaded

- name: real-restart nginx
  service:
    name: nginx
    state: restarted

- name: restart nginx freebsd
  service:
    name: nginx
    state: restarted
  when: ansible_distribution == "FreeBSD"

- name: setup
  action: setup
