---

- name: Converge
  hosts: all
  gather_facts: true
  vars_files:
    - vars/misc.yml
  vars:
    nginx_debug_role: true
  tasks:
    - name: SHELL | Get ngrok public address
      ansible.builtin.shell: set -o pipefail && curl 'http://127.0.0.1:4040/api/tunnels/command_line' 2> /dev/null | jq -r '.public_url' | cut -d '/' -f 3
      args:
        executable: /bin/bash
      register: ngrok
      changed_when: false

    - name: Include role
      ansible.builtin.include_role:
        name: "hanxhx.nginx"
