---

name: Molecule

'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - debian-11
          - debian-12
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
        allowed-to-fail:
          - false
        include:
          - scenario: debian-13
            allowed-to-fail: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@v2.7.62
        with:
          molecule_options: --base-config molecule/_shared/base.yml
          molecule_args: --scenario-name ${{ matrix.scenario }}
        continue-on-error: ${{ matrix.allowed-to-fail }}

      - name: Fake command
        run: echo "End of job"
